name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CI: true
  gitVersion: ${{ github.ref }}
  NODE_VERSION: "18.12.1"

jobs:
  build:
    runs-on: ubuntu-22.04

    if: github.actor != 'dependabot[bot]'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install Node JS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install
        run: npm ci

      - name: Test
        run: npm test
